'''
Created on Oct 13, 2014

@author: Richard
'''
INITIALIZATION_SCREEN_SIZE = (400, 530)
INITIALIZATION_SCREEN_POSITION = None
INITIALIZATION_CENTERED = True
from constants.colours import WHITE_CYAN
INITIALIZATION_BACKGROUND = WHITE_CYAN
