'''
Created on Mar 26, 2016

@author: Richard
'''
BUBBLE_CLUSTER_RESIZE_BIG_WIDTH_SCALE = 1
BUBBLE_CLUSTER_RESIZE_BIG_HEIGHT_SCALE = 1
BUBBLE_CLUSTER_RESIZE_SMALL_WIDTH_SCALE = 0.5
BUBBLE_CLUSTER_RESIZE_SMALL_HEIGHT_SCALE = 0.5